### PR TITLE
feat: add rust-bitflags

### PR DESCRIPTION
**Pull request by xzy-bit**
This contains the source for the Rust bitflags crate, packaged by debcargo for use with cargo and dh-cargo.

Log: add rust-bitflags
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/13
Task: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/6
Influence: rust-bitflags will be added

### CODE REVIEW

**Review by xzl01 — CHANGES_REQUESTED** [review]
不要使用task字段

**Comment by Zeno-sole** [comment]
存在编译过程中的产物，需删除

**Comment by Zeno-sole** [comment]
https://build.deepin.com/package/show/deepin:CI:deepin-community:rust-bitflags:PR-1/rust-bitflags  已构建通过

**Pull request merged**
